version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  todo-service:
    restart: always
    build:
      context: ./backend/todo-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mysql
      

  user-service:
    restart: always
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    depends_on:
      - mysql

  api-gateway:
    restart: always
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - todo-service
      - user-service
    