version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"