version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: db_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my-database
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend_network

  todo-service:
    restart: always
    container_name: todo-service
    build:
      context: ./backend/todo-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - backend_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=my-database
      - JWT_SECRET="supersecret"

  user-service:
    restart: always
    container_name: user-service
    build:
      context: ./backend/user-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend_network
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=my-database
      - JWT_SECRET="supersecret"

  api-gateway:
    restart: always
    container_name: api-gateway
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    networks:
      - backend_network
    environment:
      - JWT_SECRET="supersecret"
    depends_on:
      - todo-service
      - user-service


networks:
  backend_network:
    driver: bridge
